### ISSUE TITLE
Deleted comments

### ISSUE THREAD

**Issue by bhuvanakundumani** [hadarishav/Ruddit#2]
Hi,

Noted some of the comments are deleted in Reddit. Is there a way to get the deleted comments ? Thanks

**Comment by sohisudhir** [comment]
Hello, 

All the comments we used during the creation of the dataset were available at the time of its creation. Their unavailability now points towards the possibility of them being removed as per user's request. Unfortunately, there is no way to access such comments unless they were extracted before a request for removal was posted.

**Comment by bhuvanakundumani** [comment]
okay Thanks @sohisudhir
