### ISSUE TITLE
Where could I download HateBERT prefined on Ruddit dataset?

### ISSUE THREAD

**Issue by ghost** [hadarishav/Ruddit#4]

**Comment by sohisudhir** [comment]
Hi! Thanks for the issue.

Unfortunately, we cannot provide the fine-tuned hatebert model on our dataset. However, you can find the hatebert model [here](https://osf.io/tbd58/?view_onlycb79b3228d4248ddb875eb1803525ad8) and fine-tune it after extracting the Ruddit dataset. We have provided the comment ids for the same.

For extracting the comments/posts, you can use the [Reddit API](https://www.reddit.com/dev/api/) or the [Pushshift API.](https://github.com/pushshift/api) As also mentioned in the paper, we accessed the [Pushshift repository](https://arxiv.org/abs/2001.08435) using Google BigQuery.

A sample query, in case you use Google BigQuery is:
```
SELECT id, body, subreddit,
FROM `fh-bigquery.reddit_comments.201*` WHERE REGEXP_CONTAINS(_TABLE_SUFFIX, r"^([5-9]_[0-1][0-9])$")
and id in (<enter comment ids here>)
```

This query extracts data related to comments. You can choose the fields that best suit your interest. For contents related to posts, a different table (`fh-bigquery.reddit_posts`) can be queried.
